name: xml
version: 3.0.0
author: Lukas Renggli <renggli@gmail.com>
description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  petitparser: ^1.5.0
  collection: ^1.14.0
dev_dependencies:
  test: ^0.12.0
