name: pedantic
version: 1.4.0
description: How to get the most value from Dart static analysis.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pedantic

environment:
  sdk: '>=2.0.0 <3.0.0'
